name: test-workflow
on: [push]
jobs:
  test-job:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Print a message
        run: echo "Hello from GitHub Actions!"
